name: "Build"

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5.0.0
      - uses: actions/setup-node@v5.0.0
        with:
          node-version: '22.19.0'
      - name: Dummy KV DB
        run: |
          ls
          cd code/kv_bash
          source kv.sh
          kset foo bar
          kget foo
          kget bar
      - name: Build Images
        run: |
          cd code
          chmod +x *.sh
          ./start.sh
          ./stop.sh
  release:
    needs:
      - build
    if: github.event_name == 'push'
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
      - name: Install Node
        uses: actions/setup-node@v5.0.0
        with:
          node-version-file: package.json
      - name: ZIP build
        run: zip -r slides.zip slides
      - name: Release
        run: |
          npm install
          npx semantic-release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
